font_family      JetBrainsMono Nerd Font
font_size        11
disable_ligatures no

remember_window_size   no
initial_window_width   640
initial_window_height  480
window_padding_width   27
confirm_os_window_close 0

cursor_shape           block
cursor_blink_interval  0
url_style              curly

shell                  zsh
shell_integration      disabled
sync_to_monitor        no
enable_audio_bell      no

background_opacity     0.80

include current-theme.conf
